morning = input('What do you want to do in the morning?')
afternoon = input('What do you want to do in the afternoon?')
evening = input('What do you want to do in the evening?')
print(morning)
print(afternoon)
print(evening)